ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS builder

ARG BUILD_PKGS="ruby3.2-dev gcc make cmake pkg-config libssl-dev libc6-dev libssh2-1-dev libgpgme-dev libassuan-dev libgpg-error-dev"
ARG R10K_VERSION=5.0.0
ARG RUGGED_VERSION=1.9.0
ARG GPGME_VERSION=2.0.24
ARG HIERA_EYAML_GPG_VERSION=0.7.4

RUN apt-get update && \
    apt-get install -y --no-install-recommends $BUILD_PKGS && \
    gem install --no-doc r10k -v $R10K_VERSION && \
    gem install --no-doc rugged -v $RUGGED_VERSION -- --with-ssh && \
    gem install --no-doc gpgme -v $GPGME_VERSION -- --use-system-libraries && \
    gem install --no-doc hiera-eyaml-gpg -v $HIERA_EYAML_GPG_VERSION

FROM ubuntu:${UBUNTU_VERSION} AS final

ARG vcs_ref
ARG build_type
ARG build_date
ARG PACKAGES="git netbase openssh-client libssh2-1 dumb-init gpg"
ARG UBUNTU_VERSION=24.04
ARG OPENVOX_RELEASE=8
ARG OPENVOXSERVER_VERSION=8.8.0-1+ubuntu${UBUNTU_VERSION}
ARG OPENVOXDB_VERSION=8.9.0-1+ubuntu${UBUNTU_VERSION}
ARG OPENVOX_USER_UID=999
ARG OPENVOX_USER_GID=999
ARG OPENVOX_RELEASE_PACKAGE=openvox${OPENVOX_RELEASE}-release-ubuntu${UBUNTU_VERSION}.deb
ARG GPGME_VERSION=2.0.24

LABEL org.label-schema.maintainer="Voxpupuli Team <voxpupuli@groups.io>" \
      org.label-schema.vendor="OpenVoxProject" \
      org.label-schema.url="https://github.com/OpenVoxProject/container-openvoxserver" \
      org.label-schema.vcs-url="https://github.com/OpenVoxProject/container-openvoxserver" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.dockerfile="/Containerfile" \
      org.label-schema.name="OpenVox Server ($build_type)" \
      org.label-schema.version="$OPENVOXSERVER_VERSION" \
      org.label-schema.vcs-ref="$vcs_ref" \
      org.label-schema.build-date="$build_date"

ENV AUTOSIGN=true \
    CA_ALLOW_SUBJECT_ALT_NAMES=false \
    CA_ENABLED=true \
    CA_TTL=157680000 \
    CA_HOSTNAME=puppet \
    CA_PORT=8140 \
    CERTNAME="" \
    CSR_ATTRIBUTES='{}' \
    DEBIAN_FRONTEND=noninteractive \
    DNS_ALT_NAMES="" \
    ENVIRONMENTPATH=/etc/puppetlabs/code/environments \
    HIERACONFIG='$confdir/hiera.yaml' \
    INTERMEDIATE_CA_BUNDLE=/etc/puppetlabs/intermediate/ca.pem \
    INTERMEDIATE_CA_KEY=/etc/puppetlabs/intermediate/key.pem \
    INTERMEDIATE_CA=false \
    INTERMEDIATE_CRL_CHAIN=/etc/puppetlabs/intermediate/crl.pem \
    LOGDIR=/var/log/puppetlabs/puppetserver \
    OPENVOX_REPORTS="puppetdb" \
    OPENVOX_STORECONFIGS_BACKEND="puppetdb" \
    OPENVOX_STORECONFIGS=true \
    OPENVOXDB_SERVER_URLS=https://openvoxdb:8081 \
    OPENVOXSERVER_ENABLE_ENV_CACHE_DEL_API=true \
    OPENVOXSERVER_ENVIRONMENT_TIMEOUT=unlimited \
    OPENVOXSERVER_GRAPHITE_EXPORTER_ENABLED=false \
    OPENVOXSERVER_GRAPHITE_HOST=exporter \
    OPENVOXSERVER_GRAPHITE_PORT=9109 \
    OPENVOXSERVER_HOSTNAME="" \
    OPENVOXSERVER_JAVA_ARGS="-Xms1024m -Xmx1024m" \
    OPENVOXSERVER_MAX_ACTIVE_INSTANCES=1 \
    OPENVOXSERVER_MAX_REQUESTS_PER_INSTANCE=0 \
    OPENVOXSERVER_PORT=8140 \
    PATH=$PATH:/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin \
    SSLDIR=/etc/puppetlabs/puppet/ssl \
    USE_OPENVOXDB=true

COPY docker-entrypoint.sh \
     healthcheck.sh \
     Containerfile \
     /

COPY docker-entrypoint.d /docker-entrypoint.d
COPY --from=builder /var/lib/gems/ /var/lib/gems/
COPY --from=builder /usr/local/bin/r10k /usr/local/bin/
RUN mkdir -p /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems /opt/puppetlabs/server/data/puppetserver/jruby-gems/specifications
COPY --from=builder /var/lib/gems/*/gems/gpgme-${GPGME_VERSION} /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/gpgme-${GPGME_VERSION}
COPY --from=builder /var/lib/gems/*/specifications/gpgme-${GPGME_VERSION}.gemspec /opt/puppetlabs/server/data/puppetserver/jruby-gems/specifications/gpgme-${GPGME_VERSION}.gemspec

ADD https://apt.overlookinfratech.com/openvox${OPENVOX_RELEASE}-release-ubuntu${UBUNTU_VERSION}.deb /
RUN apt-get update && \
    apt-get install -y ca-certificates /${OPENVOX_RELEASE_PACKAGE} && \
    rm /${OPENVOX_RELEASE_PACKAGE}

RUN groupadd -g ${OPENVOX_USER_GID} puppet && \
    useradd -m -u ${OPENVOX_USER_UID} -g puppet puppet && \
    chmod +x /docker-entrypoint.sh /healthcheck.sh /docker-entrypoint.d/*.sh && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        $PACKAGES \
        openvoxdb-termini=${OPENVOXDB_VERSION} \
        openvox-server=${OPENVOXSERVER_VERSION} \
        && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    cp -pr /etc/puppetlabs/puppet /var/tmp && \
    cp -pr /opt/puppetlabs/server/data/puppetserver /var/tmp && \
    rm -rf /var/tmp/puppet/ssl

# needs to be copied after package installation
COPY puppetserver /etc/default/puppetserver

COPY logback.xml \
     request-logging.xml \
     /etc/puppetlabs/puppetserver/

COPY conf.d/puppetserver.conf \
     conf.d/product.conf \
     /etc/puppetlabs/puppetserver/conf.d/

COPY puppetdb.conf /var/tmp/puppet/

# k8s uses livenessProbe, startupProbe, readinessProbe and ignores HEALTHCHECK
HEALTHCHECK --interval=20s --timeout=15s --retries=12 --start-period=3m CMD ["/healthcheck.sh"]

# NOTE: this is just documentation on defaults
EXPOSE 8140

ENTRYPOINT ["dumb-init", "/docker-entrypoint.sh"]
CMD ["foreground"]
